title: "Seho Jeong"
description: "I am a Master's student in Economics, applying to Ph.D. programs in Economics and Finance for Fall 2027."
url: "https://jeong-seho.github.io"
baseurl: ""

markdown: kramdown

nav:
  - title: Home
    url: "#home"
  - title: Research
    url: "#research"
  - title: Experience
    url: "#experience"
